#!/usr/bin/env python3
"""collection_manifest.py — single source of truth for the canonical collection.

Answers "what IS the collection?" with a concrete artifact instead of a stale memory
of "~110 templates". Reads every workspace/templates/*.json, buckets each by its
HONEST status (not by a hand-remembered count), and writes a manifest the team can
actually work onward from.

Buckets (priority order — a template lands in the FIRST that matches):
  BROKEN          verified_status contains 'stable_fail'  -> known-failing, do not ship
  VERIFIED_CORE   motion_controllers.verified non-empty OR verified_status has
                  'stable_ok' / 'function-gate ✓' -> the trusted, gate-passed deliverable
                  set. THIS is "the collection" to compose from.
  DELIVERY_TODO   has cube_paths/source_paths but not verified -> a real delivery
                  template whose gate status is unknown/unverified (the work pool)
  NON_DELIVERY    no cube/source-paths -> benchmark / ros2-emit / plumbing / diagnostic.
                  Doesn't deliver objects; measured by a different (or no) gate.
  DRAFT           no status, no delivery args -> scaffolding / research one-off / stub

Zero-boot (no Kit). Usage: collection_manifest.py [--write]   (--write -> docs/notes/)
"""
import json, glob, os, sys
from collections import defaultdict

REPO = "/home/anton/projects/Omniverse_Nemotron_Ext"
TPL_DIR = os.path.join(REPO, "workspace", "templates")
MANIFEST = os.path.join(REPO, "docs", "notes", "CANONICAL_COLLECTION_MANIFEST.md")


def family(name):
    if name.startswith("CP-NEW"):
        return "CP-NEW"
    if name.startswith("CP-") and name[3:].split("-")[0].isdigit():
        return "CP-NN"
    return "named"


def classify(t):
    vs = (t.get("verified_status") or "")
    mc = t.get("motion_controllers") or {}
    verified = mc.get("verified")
    sa = t.get("simulate_args") or t.get("verify_args") or {}
    has_delivery = bool(sa.get("cube_paths") or sa.get("source_paths") or sa.get("cube_path"))
    if "stable_fail" in vs:
        return "BROKEN", has_delivery
    if (verified) or ("stable_ok" in vs) or ("function-gate ✓" in vs):
        return "VERIFIED_CORE", has_delivery
    if has_delivery:
        return "DELIVERY_TODO", has_delivery
    if vs or t.get("code_template") or t.get("roles"):
        return "NON_DELIVERY", has_delivery
    return "DRAFT", has_delivery


def main():
    rows = []
    for f in sorted(glob.glob(os.path.join(TPL_DIR, "*.json"))):
        name = os.path.basename(f)[:-5]
        try:
            t = json.load(open(f))
        except Exception:
            rows.append((name, "DRAFT", family(name), False, "parse-error"))
            continue
        bucket, hd = classify(t)
        mc = (t.get("motion_controllers") or {}).get("verified")
        rows.append((name, bucket, family(name), hd, mc or ""))

    by_bucket = defaultdict(list)
    fam_x_bucket = defaultdict(lambda: defaultdict(int))
    for name, bucket, fam, hd, mc in rows:
        by_bucket[bucket].append((name, fam, hd, mc))
        fam_x_bucket[fam][bucket] += 1

    order = ["VERIFIED_CORE", "DELIVERY_TODO", "BROKEN", "NON_DELIVERY", "DRAFT"]
    total = len(rows)

    lines = []
    lines.append("# Canonical collection manifest — single source of truth")
    lines.append("")
    lines.append("Generated by `scripts/qa/collection_manifest.py` (zero-boot). Replaces the")
    lines.append("stale \"~110 templates\" memory with the HONEST current state of")
    lines.append("`workspace/templates/`. The **VERIFIED_CORE** bucket is the deliverable")
    lines.append("collection to compose from; the rest is work-pool / drafts / non-delivery.")
    lines.append("")
    lines.append("## Headline")
    lines.append(f"- **{total}** template JSON files on disk (the directory has accreted far past the ~110 May snapshot).")
    for b in order:
        lines.append(f"- **{b}: {len(by_bucket[b])}**")
    lines.append("")
    lines.append("## Family × bucket")
    lines.append("| family | " + " | ".join(order) + " | total |")
    lines.append("|" + "---|" * (len(order) + 2))
    for fam in ("CP-NN", "CP-NEW", "named"):
        cells = [str(fam_x_bucket[fam][b]) for b in order]
        tot = sum(fam_x_bucket[fam][b] for b in order)
        lines.append(f"| {fam} | " + " | ".join(cells) + f" | {tot} |")
    lines.append("")
    for b in order:
        items = sorted(by_bucket[b])
        lines.append(f"## {b} ({len(items)})")
        if b == "VERIFIED_CORE":
            lines.append("_The trusted deliverable. mc = motion_controllers.verified._")
        for name, fam, hd, mc in items:
            tag = f" — mc={mc}" if mc else ""
            dtag = "" if hd else " [non-delivery]"
            lines.append(f"- `{name}` ({fam}){tag}{dtag}")
        lines.append("")

    out = "\n".join(lines)
    if "--write" in sys.argv:
        open(MANIFEST, "w").write(out)
        sys.stderr.write(f"wrote {MANIFEST}\n")
    # Always print the headline + family table to stderr for a quick read
    sys.stderr.write(f"\nTotal: {total}\n")
    for b in order:
        sys.stderr.write(f"  {b:14s} {len(by_bucket[b]):4d}\n")
    sys.stderr.write("\n  family   " + "  ".join(f"{b[:5]:>5s}" for b in order) + "\n")
    for fam in ("CP-NN", "CP-NEW", "named"):
        sys.stderr.write(f"  {fam:7s} " + "  ".join(f"{fam_x_bucket[fam][b]:5d}" for b in order) + "\n")


if __name__ == "__main__":
    main()
